version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - PORT=8080
      - GCP_PROJECT_ID=${GCP_PROJECT_ID}
      - DOCAI_LOCATION=us
      - DOCAI_PROCESSOR_ID=${DOCAI_PROCESSOR_ID}
      - GCS_BUCKET=${GCS_BUCKET}
      - BQ_DATASET_ID=bcc_portal
      - BQ_TABLE_ID=survey_responses
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_APP_PASSWORD=${EMAIL_APP_PASSWORD}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - FRONTEND_URL=http://localhost:3000
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev
    networks:
      - bcc-network

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8080
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - bcc-network

networks:
  bcc-network:
    driver: bridge

volumes:
  node_modules_backend:
  node_modules_frontend:
